version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: some_secure_password
      MYSQL_DATABASE: myappdb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: another_secure_password
    volumes:

      - db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  node-service:
    build: ./api
    restart: always
    environment:
      DB_HOST: db
      DB_USERNAME: mysqluser
      DB_PASSWORD: another_secure_password
      DB_NAME: myappdb
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - node-service

volumes:
  db-data:
